name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Install sed
        run: sudo apt-get install -y sed

      - name: Convert Markdown to HTML
        run: |
          mkdir -p public
          mkdir -p public/Documentation
          pandoc README.md -s --no-highlight --template building/html/index.html -o public/index.html
          sed -i 's/\.md"/\.html"/g' "public/index.html"
          pandoc Documentation/Application.md -p -s --no-highlight --template building/html/index.html -o public/Documentation/Application.html   
          
         
      - name: Copy CSS
        run: cp building/html/index.css public/index.css

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages